# encoding: utf-8

import gvsig

from org.gvsig.fmap.dal import DALLocator

def add_attribute_LID_IMDS(ft):
  attr = ft.add("LID_IMDS",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LID_IMDS')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(True)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Id_Imds')
  attr.setOrder(0)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ANO(ft):
  attr = ft.add("ANO",19)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'Año')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AÑO')
  attr.setOrder(1)
  attr.setPrecision(16)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  
def add_attribute_TRAMO(ft):
  attr = ft.add("TRAMO",8)
  attr.setSize(254)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TRAMO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'TRAMO')
  attr.setOrder(5)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_LONGITUD(ft):
  attr = ft.add("LONGITUD",19)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LONGITUD')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'LONGITUD')
  attr.setOrder(10)
  attr.setPrecision(16)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_CTRA(ft):
  attr = ft.add("CTRA",8)
  attr.setSize(50)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CTRA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'CTRA')
  attr.setOrder(20)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_TIPO(ft):
  attr = ft.add("TIPO",8)
  attr.setSize(50)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TIPO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'TIPO')
  attr.setOrder(30)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_TIT(ft):
  attr = ft.add("TIT",8)
  attr.setSize(50)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TIT')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'TIT')
  attr.setOrder(40)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_PK_INI(ft):
  attr = ft.add("PK_INI",8)
  attr.setSize(50)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PK_INI')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'PK_INI')
  attr.setOrder(50)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_DESDE(ft):
  attr = ft.add("DESDE",8)
  attr.setSize(254)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'DESDE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'DESDE')
  attr.setOrder(60)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_PK_FIN(ft):
  attr = ft.add("PK_FIN",8)
  attr.setSize(50)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PK_FIN')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'PK_FIN')
  attr.setOrder(70)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_HASTA(ft):
  attr = ft.add("HASTA",8)
  attr.setSize(254)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'HASTA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'HASTA')
  attr.setOrder(80)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_CALZADA(ft):
  attr = ft.add("CALZADA",8)
  attr.setSize(254)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CALZADA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'CALZADA')
  attr.setOrder(90)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_PK_EST(ft):
  attr = ft.add("PK_EST",8)
  attr.setSize(50)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PK_EST')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'PK_EST')
  attr.setOrder(100)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_IMD18(ft):
  attr = ft.add("IMD18",5)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'IMD18')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'IMD18')
  attr.setOrder(110)
  attr.setPrecision(19)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ZP18(ft):
  attr = ft.add("ZP18",19)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ZP18')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ZP18')
  attr.setOrder(120)
  attr.setPrecision(14)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_GEOMETRY(ft):
  attr = ft.add("GEOMETRY",66)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'GEOMETRY')
  attr.setGeometryType(21, 0)
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'GEOMETRY')
  attr.setOrder(130)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSRS(u'EPSG:4326(+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs )')

def add_attributes_imds_2018(ft):
  add_attribute_LID_IMDS(ft)
  add_attribute_ANO(ft)
  add_attribute_TRAMO(ft)
  add_attribute_LONGITUD(ft)
  add_attribute_CTRA(ft)
  add_attribute_TIPO(ft)
  add_attribute_TIT(ft)
  add_attribute_PK_INI(ft)
  add_attribute_DESDE(ft)
  add_attribute_PK_FIN(ft)
  add_attribute_HASTA(ft)
  add_attribute_CALZADA(ft)
  add_attribute_PK_EST(ft)
  add_attribute_IMD18(ft)
  add_attribute_ZP18(ft)
  add_attribute_GEOMETRY(ft)


def configurar_featuretype_imds_2018(ft):

  add_attributes_imds_2018(ft)

def crearTabla_imds_2018(connection):
  tableName = "imds_2018"
  dataManager = DALLocator.getDataManager()
  server = dataManager.openServerExplorer(
      connection.getProviderName(),
      connection
  )
  params = server.getAddParameters(tableName)
  ft = params.getDefaultFeatureType()
  configurar_featuretype_imds_2018(ft)
  
  server.add(tableName, params, False)

def main(*args):
    pass
