# encoding: utf-8

import gvsig

from org.gvsig.fmap.dal import DALLocator
from org.gvsig.tools.dataTypes import DataTypes

def add_attribute_COD_AFORO(ft):
  attr = ft.add("COD_AFORO",DataTypes.STRING)
  attr.setSize(40)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'COD_AFORO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(True)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Cod_Aforo')
  attr.setOrder(0)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setDefaultFieldValue("<%=replace(UUID(),'-','')%>");
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_COD_ESTACI(ft):
  attr = ft.add("COD_ESTACI",DataTypes.STRING)
  attr.setSize(40)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'COD_ESTACI')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Cod_Estacion_Aforo')
  attr.setOrder(0)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  

def add_attribute_E_TRAMO(ft):
  attr = ft.add("E_TRAMO", DataTypes.STRING)
  attr.setSize(16)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'E_TRAMO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Tramo')
  attr.setOrder(5)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  
def add_attribute_E_PROV(ft):
  attr = ft.add("E_PROV", DataTypes.INT)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'E_PROV')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Provincia')
  attr.setOrder(5)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_LONG(ft):
  attr = ft.add("E_LONG", DataTypes.DECIMAL)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'E_LONG')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Longitud')
  attr.setOrder(10)
  attr.setPrecision(12)
  attr.setScale(3)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_CTRA(ft):
    attr = ft.add("E_CTRA", DataTypes.STRING)
    attr.setSize(50)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'CARRETERA')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Carretera')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_E_TIPO(ft):
  attr = ft.add("E_TIPO", DataTypes.STRING)
  attr.setSize(5)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_TIPO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Tipo_estacion')
  attr.setOrder(90)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_TIT(ft):
  attr = ft.add("E_TIT", DataTypes.STRING)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TITULARIDAD')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Titularidad')
  attr.setOrder(5)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_PK_INI(ft):
  attr = ft.add("E_PK_INI", DataTypes.DECIMAL)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'E_PK_INI')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Pk_inicio')
  attr.setOrder(10)
  attr.setPrecision(9)
  attr.setScale(3)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_INICIO(ft):
  attr = ft.add("E_INICIO", DataTypes.STRING)
  attr.setSize(256)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'E_INICIO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Punto_Inicio')
  attr.setOrder(60)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_PK_FIN(ft):
  attr = ft.add("E_PK_FIN", DataTypes.DECIMAL)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'E_PK_FIN')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Pk_Final')
  attr.setOrder(70)
  attr.setPrecision(9)
  attr.setScale(3)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_FIN(ft):
  attr = ft.add("E_FIN", DataTypes.STRING)
  attr.setSize(256)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'E_FIN')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Punto_final')
  attr.setOrder(80)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_CALZADA(ft):
  attr = ft.add("E_CALZADA", DataTypes.STRING)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'E_CALZADA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'CALZADA')
  attr.setOrder(90)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_PK_EST(ft):
  attr = ft.add("E_PK_EST", DataTypes.DECIMAL)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'E_PK_EST')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'PK_EST')
  attr.setOrder(100)
  attr.setPrecision(9)
  attr.setScale(3)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_E_EXTRA(ft):
  attr = ft.add("E_EXTRA", DataTypes.STRING)
  attr.setSize(10000)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'Extra')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Extra')
  attr.setOrder(2000)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  
def add_attributes_estaciones(ft):
    add_attribute_COD_AFORO(ft)
    add_attribute_COD_ESTACI(ft)
    add_attribute_E_TRAMO(ft)
    add_attribute_E_PROV(ft)
    add_attribute_E_LONG(ft)
    add_attribute_E_CTRA(ft)
    add_attribute_E_TIPO(ft)
    add_attribute_E_TIT(ft)
    add_attribute_E_PK_INI(ft)
    add_attribute_E_INICIO(ft)
    add_attribute_E_PK_FIN(ft)
    add_attribute_E_FIN(ft)
    add_attribute_E_CALZADA(ft)
    add_attribute_E_PK_EST(ft)
    add_attribute_E_EXTRA(ft)





def configurar_featuretype_estaciones(ft):

  add_attributes_estaciones(ft)

def crearTabla_estaciones(connection):
  tableName = "AFOROS_ESTACIONES"
  dataManager = DALLocator.getDataManager()
  server = dataManager.openServerExplorer(
      connection.getProviderName(),
      connection
  )
  params = server.getAddParameters(tableName)
  ft = params.getDefaultFeatureType()
  configurar_featuretype_estaciones(ft)

  server.add(tableName, params, False)

def main(*args):
    pass
