# encoding: utf-8

import gvsig

from org.gvsig.fmap.dal import DALLocator
from org.gvsig.tools.dataTypes import DataTypes

def add_attribute_COD_AFORO(ft):
  attr = ft.add("COD_AFORO",DataTypes.STRING)
  attr.setSize(40)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'COD_AFORO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(True)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Cod_Aforo')
  attr.setOrder(0)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setDefaultFieldValue("<%=replace(UUID(),'-','')%>");
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  
def add_attribute_COD_ESTACI(ft):
  attr = ft.add("COD_ESTACI",DataTypes.STRING)
  attr.setSize(40)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'COD_ESTACI')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Cod_Estacion_Aforo')
  attr.setOrder(0)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  
def add_attribute_M_PROV(ft):
  attr = ft.add("M_PROV", DataTypes.INT)
  #attr.setSize(254)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_PROV')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Provincia')
  attr.setOrder(5)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_TIT(ft):
  attr = ft.add("M_TIT", DataTypes.STRING)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TITULARIDAD')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Titularidad')
  attr.setOrder(5)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_CTRA(ft):
    attr = ft.add("M_CTRA", DataTypes.STRING)
    attr.setSize(50)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'CARRETERA')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Carretera')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_TRAMO(ft):
  attr = ft.add("M_TRAMO", DataTypes.STRING)
  attr.setSize(16)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TRAMO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Tramo')
  attr.setOrder(5)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_PK_INI(ft):
  attr = ft.add("M_PK_INI", DataTypes.DECIMAL)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_PK_INI')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Pk_inicio')
  attr.setOrder(10)
  attr.setPrecision(9)
  attr.setScale(3)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_INICIO(ft):
  attr = ft.add("M_INICIO", DataTypes.STRING)
  attr.setSize(256)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_INICIO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Punto_Inicio')
  attr.setOrder(60)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_PK_FIN(ft):
  attr = ft.add("M_PK_FIN", DataTypes.DECIMAL)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_PK_FIN')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Pk_Final')
  attr.setOrder(70)
  attr.setPrecision(9)
  attr.setScale(3)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_FIN(ft):
  attr = ft.add("M_FIN", DataTypes.STRING)
  attr.setSize(256)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_FIN')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Punto_final')
  attr.setOrder(80)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_CALZADA(ft):
  attr = ft.add("M_CALZADA", DataTypes.STRING)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CALZADA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'CALZADA')
  attr.setOrder(90)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_PK_EST(ft):
  attr = ft.add("M_PK_EST", DataTypes.DECIMAL)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PK_EST')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'PK_EST')
  attr.setOrder(100)
  attr.setPrecision(9)
  attr.setScale(3)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_TIPO(ft):
  attr = ft.add("M_TIPO", DataTypes.STRING)
  attr.setSize(5)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_TIPO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Tipo_estacion')
  attr.setOrder(90)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_GRUPO(ft):
  attr = ft.add("M_GRUPO", DataTypes.STRING)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_GRUPO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Grupo_temporal')
  attr.setOrder(90)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_FECHA(ft):
  attr = ft.add("M_FECHA", DataTypes.DATE)
  #attr.setSize(10)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_FECHA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Fecha')
  attr.setOrder(90)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_ANO(ft):
  attr = ft.add("M_ANO", DataTypes.INT)
  #attr.setSize(254)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'M_ANO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Anyo')
  attr.setOrder(5)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_M_MES(ft):
    attr = ft.add("M_MES", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_MES')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Mes')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_DIA(ft):
    attr = ft.add("M_DIA", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_DIA')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Dia')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_HORA(ft):
    attr = ft.add("M_HORA", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_HORA')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Hora')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_DIA_SEMANA(ft):
    attr = ft.add("M_DIA_SEM", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_DIA_SEM')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Dia_semana')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_TOTVEH(ft):
    attr = ft.add("M_TOTVEH", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_TOTVEH')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Total_vehiculos')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_TOTVEHP(ft):
    attr = ft.add("M_TOTVEHP", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_TOTVEHP')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Total_vehiculos_pesados')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_TOTVEHL(ft):
    attr = ft.add("M_TOTVEHL", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_TOTVEHL')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Total_vehiculos_ligeros')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_ZP(ft):
    attr = ft.add("M_ZP", DataTypes.DECIMAL)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_ZP')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Porcentaje_pesados')
    attr.setOrder(5)
    attr.setPrecision(6)
    attr.setScale(3)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_IM(ft):
    attr = ft.add("M_IM", DataTypes.DECIMAL)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_IM')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Intensidad_media_diaria')
    attr.setOrder(5)
    attr.setPrecision(9)
    attr.setScale(3)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_IM_PES(ft):
    attr = ft.add("M_IM_PES", DataTypes.DECIMAL)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_IM_PES')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Intensidad_media_diaria_pesados')
    attr.setOrder(5)
    attr.setPrecision(9)
    attr.setScale(3)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_IM_LIG(ft):
    attr = ft.add("M_IM_LIG", DataTypes.DECIMAL)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_IM_LIG')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'_Intensidad_media_diaria_ligeros')
    attr.setOrder(5)
    attr.setPrecision(9)
    attr.setScale(3)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VTSECV50(ft):
    attr = ft.add("M_VTSECV50", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VTSECV50')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media total seccion V50')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VTSECV85(ft):
    attr = ft.add("M_VTSECV85", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VTSECV85')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media total seccion V85')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VTSECV99(ft):
    attr = ft.add("M_VTSECV99", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VTSECV99')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media total seccion V99')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VTASCV50(ft):
    attr = ft.add("M_VTASCV50", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VTASCV50')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media total asc V50')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VTASCV85(ft):
    attr = ft.add("M_VTASCV85", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VTASCV85')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media total asc V85')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VTASCV99(ft):
    attr = ft.add("M_VTASCV99", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VTASCV99')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media total asc V99')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VTDESV50(ft):
    attr = ft.add("M_VTDESV50", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VTDESV50')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media total des V50')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VTDESV85(ft):
    attr = ft.add("M_VTDESV85", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VTDESV85')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media total des V85')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VTDESV99(ft):
    attr = ft.add("M_VTDESV99", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VTDESV99')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media total des V99')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VLSECV50(ft):
    attr = ft.add("M_VLSECV50", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VLSECV50')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media ligeros seccion V50')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VLSECV85(ft):
    attr = ft.add("M_VLSECV85", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VLSECV85')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media ligeros seccion V85')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VLSECV99(ft):
    attr = ft.add("M_VLSECV99", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VLSECV99')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media ligeros seccion V99')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VLASCV50(ft):
    attr = ft.add("M_VLASCV50", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VLASCV50')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media ligeros asc V50')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VLASCV85(ft):
    attr = ft.add("M_VLASCV85", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VLASCV85')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media ligeros asc V85')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VLASCV99(ft):
    attr = ft.add("M_VLASCV99", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VLASCV99')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media ligeros asc V99')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VLDESV50(ft):
    attr = ft.add("M_VLDESV50", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VLDESV50')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media ligeros des V50')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VLDESV85(ft):
    attr = ft.add("M_VLDESV85", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VLDESV85')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media ligeros des V85')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VLDESV99(ft):
    attr = ft.add("M_VLDESV99", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VLDESV99')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media ligeros des V99')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VPSECV50(ft):
    attr = ft.add("M_VPSECV50", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VPSECV50')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media pesados seccion V50')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VPSECV85(ft):
    attr = ft.add("M_VPSECV85", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VPSECV85')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media pesados seccion V85')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VPSECV99(ft):
    attr = ft.add("M_VPSECV99", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VPSECV99')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media pesados seccion V99')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VPASCV50(ft):
    attr = ft.add("M_VPASCV50", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VPASCV50')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media pesados asc V50')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VPASCV85(ft):
    attr = ft.add("M_VPASCV85", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VPASCV85')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media pesados asc V85')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VPASCV99(ft):
    attr = ft.add("M_VPASCV99", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VPASCV99')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media pesados asc V99')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VPDESV50(ft):
    attr = ft.add("M_VPDESV50", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VPDESV50')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media pesados des V50')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VPDESV85(ft):
    attr = ft.add("M_VPDESV85", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VPDESV85')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media pesados des V85')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_VPDESV99(ft):
    attr = ft.add("M_VPDESV99", DataTypes.INT)
    #attr.setSize(254)
    attr.setAllowIndexDuplicateds(True)
    attr.setAllowNull(True)
    attr.setDataProfileName(None)
    attr.setDescription(u'M_VPDESV99')
    attr.setGroup(None)
    attr.setHidden(False)
    attr.setIsAutomatic(False)
    attr.setIsIndexAscending(True)
    attr.setIsIndexed(False)
    attr.setIsPrimaryKey(False)
    attr.setIsReadOnly(False)
    attr.setIsTime(False)
    attr.setLabel(u'Velocidad media pesados des V99')
    attr.setOrder(5)
    attr.setPrecision(-1)
    attr.setReadOnly(False)
    attr.setRelationType(0)

def add_attribute_M_EXTRA(ft):
  attr = ft.add("M_EXTRA", DataTypes.STRING)
  attr.setSize(10000)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'Extra')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Extra')
  attr.setOrder(2000)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  
def add_attributes_medidas(ft):
    add_attribute_COD_AFORO(ft)
    add_attribute_COD_ESTACION_AFORO(ft)
    add_attribute_M_PROV(ft)
    add_attribute_M_TIT(ft)
    add_attribute_M_CTRA(ft)
    add_attribute_M_TRAMO(ft)
    add_attribute_M_PK_INI(ft)
    add_attribute_M_INICIO(ft)
    add_attribute_M_PK_FIN(ft)
    add_attribute_M_FIN(ft)
    add_attribute_M_CALZADA(ft)
    add_attribute_M_PK_EST(ft)
    add_attribute_M_TIPO(ft)
    add_attribute_M_GRUPO(ft)
    add_attribute_M_FECHA(ft)
    add_attribute_M_ANO(ft)
    add_attribute_M_MES(ft)
    add_attribute_M_DIA(ft)
    add_attribute_M_HORA(ft)
    add_attribute_M_DIA_SEMANA(ft)
    add_attribute_M_TOTVEH(ft)
    add_attribute_M_TOTVEHP(ft)
    add_attribute_M_TOTVEHL(ft)
    add_attribute_M_ZP(ft)
    add_attribute_M_IM(ft)
    add_attribute_M_IM_PES(ft)
    add_attribute_M_IM_LIG(ft)
    add_attribute_M_VTSECV50(ft)
    add_attribute_M_VTSECV85(ft)
    add_attribute_M_VTSECV99(ft)
    add_attribute_M_VTASCV50(ft)
    add_attribute_M_VTASCV85(ft)
    add_attribute_M_VTASCV99(ft)
    add_attribute_M_VTDESV50(ft)
    add_attribute_M_VTDESV85(ft)
    add_attribute_M_VTDESV99(ft)
    add_attribute_M_VLSECV50(ft)
    add_attribute_M_VLSECV85(ft)
    add_attribute_M_VLSECV99(ft)
    add_attribute_M_VLASCV50(ft)
    add_attribute_M_VLASCV85(ft)
    add_attribute_M_VLASCV99(ft)
    add_attribute_M_VLDESV50(ft)
    add_attribute_M_VLDESV85(ft)
    add_attribute_M_VLDESV99(ft)
    add_attribute_M_VPSECV50(ft)
    add_attribute_M_VPSECV85(ft)
    add_attribute_M_VPSECV99(ft)
    add_attribute_M_VPASCV50(ft)
    add_attribute_M_VPASCV85(ft)
    add_attribute_M_VPASCV99(ft)
    add_attribute_M_VPDESV50(ft)
    add_attribute_M_VPDESV85(ft)
    add_attribute_M_VPDESV99(ft)
    add_attribute_M_EXTRA(ft)



def configurar_featuretype_medidas(ft):

  add_attributes_medidas(ft)

def crearTabla_medidas(connection):
  tableName = "AFOROS_MEDIDAS"
  dataManager = DALLocator.getDataManager()
  server = dataManager.openServerExplorer(
      connection.getProviderName(),
      connection
  )
  params = server.getAddParameters(tableName)
  ft = params.getDefaultFeatureType()
  configurar_featuretype_medidas(ft)

  server.add(tableName, params, False)

def main(*args):
    pass
