# encoding: utf-8

import gvsig

from org.gvsig.fmap.dal import DALLocator

def add_attribute_LID_VEHICULO(ft):
  attr = ft.add("LID_VEHICULO",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LID_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(True)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(True)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'LID_VEHICULO')
  attr.setOrder(0)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ID_ACCIDENTE(ft):
  attr = ft.add("ID_ACCIDENTE",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ID_ACCIDENTE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Accidente')
  attr.setOrder(10)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.getForeingKey().setCodeName(u'ID_ACCIDENTE')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%s',ID_ACCIDENTE)")
  attr.getForeingKey().setSelectable(False)
  attr.getForeingKey().setTableName(u'ARENA2_ACCIDENTES')

def add_attribute_ID_VEHICULO(ft):
  attr = ft.add("ID_VEHICULO",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ID_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Cod.vehiculo')
  attr.setOrder(20)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_SIN_CONDUCTOR(ft):
  attr = ft.add("SIN_CONDUCTOR",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SIN_CONDUCTOR')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Sin conducor')
  attr.setOrder(30)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_LID_CONDUCTOR(ft):
  attr = ft.add("LID_CONDUCTOR",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LID_CONDUCTOR')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Conductor')
  attr.setOrder(40)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.getForeingKey().setCodeName(u'LID_CONDUCTOR')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d %s %s %s',TOINTEGER(ID_VEHICULO), TOSTR(FECHA_NACIMIENTO), NACIONALIDAD, MUNICIPIO_RESIDENCIA)")
  attr.getForeingKey().setSelectable(False)
  attr.getForeingKey().setTableName(u'ARENA2_CONDUCTORES')

def add_attribute_FECHA_MATRICULACION(ft):
  attr = ft.add("FECHA_MATRICULACION",9)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FECHA_MATRICULACION')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Fecha matriculacion')
  attr.setOrder(50)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_NACIONALIDAD(ft):
  attr = ft.add("NACIONALIDAD",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'NACIONALIDAD')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Nacionalidad')
  attr.setOrder(60)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_TIPO_VEHICULO(ft):
  attr = ft.add("TIPO_VEHICULO",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TIPO_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Tipo vehiculo')
  attr.setOrder(70)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_TIPO_VEHICULO')

def add_attribute_MARCA_NOMBRE(ft):
  attr = ft.add("MARCA_NOMBRE",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MARCA_NOMBRE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Marca')
  attr.setOrder(80)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_MODELO(ft):
  attr = ft.add("MODELO",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MODELO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Modelo')
  attr.setOrder(90)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ITV(ft):
  attr = ft.add("ITV",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ITV')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ITV')
  attr.setOrder(100)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_ITV')

def add_attribute_SEGURO(ft):
  attr = ft.add("SEGURO",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SEGURO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Seguro')
  attr.setOrder(110)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_REMOLQUE(ft):
  attr = ft.add("REMOLQUE",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'REMOLQUE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Remolque')
  attr.setOrder(120)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_SEMIREMOLQUE(ft):
  attr = ft.add("SEMIREMOLQUE",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SEMIREMOLQUE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Semiremolque')
  attr.setOrder(130)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_CARAVANA(ft):
  attr = ft.add("CARAVANA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CARAVANA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Carabana')
  attr.setOrder(140)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_REMOLQUE_OTROS(ft):
  attr = ft.add("REMOLQUE_OTROS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'REMOLQUE_OTROS')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Otros remolques')
  attr.setOrder(150)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_FACT_ANOMALIAS_PREVIAS(ft):
  attr = ft.add("FACT_ANOMALIAS_PREVIAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FACT_ANOMALIAS_PREVIAS')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'FACT_ANOMALIAS_PREVIAS')
  attr.setOrder(160)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ANOMALIAS_NINGUNA(ft):
  attr = ft.add("ANOMALIAS_NINGUNA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_NINGUNA')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_NINGUNA')
  attr.setOrder(170)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ANOMALIAS_NEUMATICOS(ft):
  attr = ft.add("ANOMALIAS_NEUMATICOS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_NEUMATICOS')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_NEUMATICOS')
  attr.setOrder(180)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ANOMALIAS_REVENTON(ft):
  attr = ft.add("ANOMALIAS_REVENTON",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_REVENTON')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_REVENTON')
  attr.setOrder(190)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ANOMALIAS_DIRECCION(ft):
  attr = ft.add("ANOMALIAS_DIRECCION",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_DIRECCION')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_DIRECCION')
  attr.setOrder(200)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ANOMALIAS_FRENOS(ft):
  attr = ft.add("ANOMALIAS_FRENOS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_FRENOS')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_FRENOS')
  attr.setOrder(210)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ANOMALIAS_OTRAS(ft):
  attr = ft.add("ANOMALIAS_OTRAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_OTRAS')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_OTRAS')
  attr.setOrder(220)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_MP(ft):
  attr = ft.add("MP",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MP')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Mercancias peligrosas')
  attr.setOrder(230)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_VEHICULO_ADAPTADO(ft):
  attr = ft.add("VEHICULO_ADAPTADO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'VEHICULO_ADAPTADO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Vehiculo adaptado')
  attr.setOrder(240)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_NUM_OCUPANTES(ft):
  attr = ft.add("NUM_OCUPANTES",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'NUM_OCUPANTES')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Numero de ocupantes')
  attr.setOrder(250)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_FUGADO(ft):
  attr = ft.add("FUGADO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FUGADO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Fugado')
  attr.setOrder(260)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_INCENDIADO(ft):
  attr = ft.add("INCENDIADO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INCENDIADO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Incendiado')
  attr.setOrder(270)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_TACOGRAFO_DISCO(ft):
  attr = ft.add("TACOGRAFO_DISCO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TACOGRAFO_DISCO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'TACOGRAFO_DISCO')
  attr.setOrder(280)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_COND(ft):
  attr = ft.add("AIRBAG_COND",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_COND')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_COND')
  attr.setOrder(290)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_PAS_DEL(ft):
  attr = ft.add("AIRBAG_PAS_DEL",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_PAS_DEL')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_PAS_DEL')
  attr.setOrder(300)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_ROD_IZDA(ft):
  attr = ft.add("AIRBAG_ROD_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_ROD_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_ROD_IZDA')
  attr.setOrder(310)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_ROD_DCHA(ft):
  attr = ft.add("AIRBAG_ROD_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_ROD_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_ROD_DCHA')
  attr.setOrder(320)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_LAT_DEL_IZDA(ft):
  attr = ft.add("AIRBAG_LAT_DEL_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_DEL_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_LAT_DEL_IZDA')
  attr.setOrder(330)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_LAT_DEL_DCHA(ft):
  attr = ft.add("AIRBAG_LAT_DEL_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_DEL_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_LAT_DEL_DCHA')
  attr.setOrder(340)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_CORT_DEL_IZDA(ft):
  attr = ft.add("AIRBAG_CORT_DEL_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_DEL_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_CORT_DEL_IZDA')
  attr.setOrder(350)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_CORT_DEL_DCHA(ft):
  attr = ft.add("AIRBAG_CORT_DEL_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_DEL_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_CORT_DEL_DCHA')
  attr.setOrder(360)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_LAT_TRAS_IZDA(ft):
  attr = ft.add("AIRBAG_LAT_TRAS_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_TRAS_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_LAT_TRAS_IZDA')
  attr.setOrder(370)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_LAT_TRAS_DCHA(ft):
  attr = ft.add("AIRBAG_LAT_TRAS_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_TRAS_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_LAT_TRAS_DCHA')
  attr.setOrder(380)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_CORT_TRAS_IZDA(ft):
  attr = ft.add("AIRBAG_CORT_TRAS_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_TRAS_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_CORT_TRAS_IZDA')
  attr.setOrder(390)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_CORT_TRAS_DCHA(ft):
  attr = ft.add("AIRBAG_CORT_TRAS_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_TRAS_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_CORT_TRAS_DCHA')
  attr.setOrder(400)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_OTROS(ft):
  attr = ft.add("AIRBAG_OTROS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_OTROS')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_OTROS')
  attr.setOrder(410)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_AIRBAG_DESCONOCIDO(ft):
  attr = ft.add("AIRBAG_DESCONOCIDO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_DESCONOCIDO')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_DESCONOCIDO')
  attr.setOrder(420)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_TRANSPORTE_ESPECIAL(ft):
  attr = ft.add("TRANSPORTE_ESPECIAL",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TRANSPORTE_ESPECIAL')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Transporte especial')
  attr.setOrder(430)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_DANYOS(ft):
  attr = ft.add("DANYOS",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'DANYOS')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Da\xf1os')
  attr.setOrder(440)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_DANYOS')

def add_attribute_POS_VIA(ft):
  attr = ft.add("POS_VIA",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'POS_VIA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'POS_VIA')
  attr.setOrder(450)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_POSICION_VIA')

def add_attribute_APROXIMACION_NUDO(ft):
  attr = ft.add("APROXIMACION_NUDO",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'APROXIMACION_NUDO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'APROXIMACION_NUDO')
  attr.setOrder(460)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_NUDO_APROX')

def add_attribute_SENTIDO_CIRCULACION(ft):
  attr = ft.add("SENTIDO_CIRCULACION",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SENTIDO_CIRCULACION')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'SENTIDO_CIRCULACION')
  attr.setOrder(470)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_SENTIDO_CIRCULA')

def add_attribute_LUGAR_CIRCULABA(ft):
  attr = ft.add("LUGAR_CIRCULABA",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LUGAR_CIRCULABA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'LUGAR_CIRCULABA')
  attr.setOrder(480)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_LUGAR_CIRCULA')

def add_attribute_FACT_LUGAR_CIRCULA(ft):
  attr = ft.add("FACT_LUGAR_CIRCULA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FACT_LUGAR_CIRCULA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'FACT_LUGAR_CIRCULA')
  attr.setOrder(490)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_PASAJEROS(ft):
  attr = ft.add("PASAJEROS",34)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PASAJEROS')
  attr.setGroup(u'Pasajeros')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(True)
  attr.setIsTime(False)
  attr.setLabel(u'PASAJEROS')
  attr.setOrder(500)
  attr.setPrecision(0)
  attr.setReadOnly(True)
  attr.setRelationType(0)
  attr.getTags().set(u'dal.relatedfeatures.unique.field', u'LID_PASAJERO')
  attr.getTags().set(u'dynform.label.empty', u'True')
  attr.getTags().set(u'dal.relatedfeatures.columns', u'ID_PASAJERO/FECHA_NACIMIENTO/SEXO/PAIS_RESIDENCIA/PROVINCIA_RESIDENCIA/MUNICIPIO_RESIDENCIA')
  attr.setFeatureAttributeEmulator(u"FEATURES('ARENA2_PASAJEROS',FORMAT('LID_VEHICULO = ''%s''',LID_VEHICULO))")

def add_attributes_ARENA2_VEHICULOS(ft):
  add_attribute_LID_VEHICULO(ft)
  add_attribute_ID_ACCIDENTE(ft)
  add_attribute_ID_VEHICULO(ft)
  add_attribute_SIN_CONDUCTOR(ft)
  add_attribute_LID_CONDUCTOR(ft)
  add_attribute_FECHA_MATRICULACION(ft)
  add_attribute_NACIONALIDAD(ft)
  add_attribute_TIPO_VEHICULO(ft)
  add_attribute_MARCA_NOMBRE(ft)
  add_attribute_MODELO(ft)
  add_attribute_ITV(ft)
  add_attribute_SEGURO(ft)
  add_attribute_REMOLQUE(ft)
  add_attribute_SEMIREMOLQUE(ft)
  add_attribute_CARAVANA(ft)
  add_attribute_REMOLQUE_OTROS(ft)
  add_attribute_FACT_ANOMALIAS_PREVIAS(ft)
  add_attribute_ANOMALIAS_NINGUNA(ft)
  add_attribute_ANOMALIAS_NEUMATICOS(ft)
  add_attribute_ANOMALIAS_REVENTON(ft)
  add_attribute_ANOMALIAS_DIRECCION(ft)
  add_attribute_ANOMALIAS_FRENOS(ft)
  add_attribute_ANOMALIAS_OTRAS(ft)
  add_attribute_MP(ft)
  add_attribute_VEHICULO_ADAPTADO(ft)
  add_attribute_NUM_OCUPANTES(ft)
  add_attribute_FUGADO(ft)
  add_attribute_INCENDIADO(ft)
  add_attribute_TACOGRAFO_DISCO(ft)
  add_attribute_AIRBAG_COND(ft)
  add_attribute_AIRBAG_PAS_DEL(ft)
  add_attribute_AIRBAG_ROD_IZDA(ft)
  add_attribute_AIRBAG_ROD_DCHA(ft)
  add_attribute_AIRBAG_LAT_DEL_IZDA(ft)
  add_attribute_AIRBAG_LAT_DEL_DCHA(ft)
  add_attribute_AIRBAG_CORT_DEL_IZDA(ft)
  add_attribute_AIRBAG_CORT_DEL_DCHA(ft)
  add_attribute_AIRBAG_LAT_TRAS_IZDA(ft)
  add_attribute_AIRBAG_LAT_TRAS_DCHA(ft)
  add_attribute_AIRBAG_CORT_TRAS_IZDA(ft)
  add_attribute_AIRBAG_CORT_TRAS_DCHA(ft)
  add_attribute_AIRBAG_OTROS(ft)
  add_attribute_AIRBAG_DESCONOCIDO(ft)
  add_attribute_TRANSPORTE_ESPECIAL(ft)
  add_attribute_DANYOS(ft)
  add_attribute_POS_VIA(ft)
  add_attribute_APROXIMACION_NUDO(ft)
  add_attribute_SENTIDO_CIRCULACION(ft)
  add_attribute_LUGAR_CIRCULABA(ft)
  add_attribute_FACT_LUGAR_CIRCULA(ft)
  add_attribute_PASAJEROS(ft)


def crearTabla_ARENA2_VEHICULOS(connection):
  tableName = "ARENA2_VEHICULOS"
  dataManager = DALLocator.getDataManager()
  server = dataManager.openServerExplorer(
      connection.getProviderName(),
      connection
  )
  params = server.getAddParameters(tableName)
  ft = params.getDefaultFeatureType()

  add_attributes_ARENA2_VEHICULOS(ft)
  
  server.add(tableName, params, False)

def main(*args):
    pass
