# encoding: utf-8

import gvsig

from org.gvsig.fmap.dal import DALLocator

def add_attribute_LID_VEHICULO(ft):
  attr = ft.add("LID_VEHICULO",8)
  attr.setSize(30)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LID_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(True)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(True)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_ID_vehiculo')
  attr.setOrder(0)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)

def add_attribute_ID_ACCIDENTE(ft):
  attr = ft.add("ID_ACCIDENTE",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ID_ACCIDENTE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Accidente')
  attr.setOrder(10)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID_ACCIDENTE')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%s',ID_ACCIDENTE)")
  attr.getForeingKey().setClosedList(False)
  attr.getForeingKey().setTableName(u'ARENA2_ACCIDENTES')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ID_VEHICULO(ft):
  attr = ft.add("ID_VEHICULO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ID_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Cod_vehiculo')
  attr.setOrder(20)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_SIN_CONDUCTOR(ft):
  attr = ft.add("SIN_CONDUCTOR",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SIN_CONDUCTOR')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Sin_conductor')
  attr.setOrder(30)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_LID_CONDUCTOR(ft):
  attr = ft.add("LID_CONDUCTOR",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LID_CONDUCTOR')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Conductor')
  attr.setOrder(40)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'LID_CONDUCTOR')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d %s %s %s',TOINTEGER(ID_VEHICULO), TOSTR(FECHA_NACIMIENTO), NACIONALIDAD, MUNICIPIO_RESIDENCIA)")
  attr.getForeingKey().setClosedList(False)
  attr.getForeingKey().setTableName(u'ARENA2_CONDUCTORES')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_FECHA_MATRICULACION(ft):
  attr = ft.add("FECHA_MATRICULACION",9)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FECHA_MATRICULACION')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Fecha_matriculacion')
  attr.setOrder(50)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_NACIONALIDAD(ft):
  attr = ft.add("NACIONALIDAD",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'NACIONALIDAD')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Nacionalidad')
  attr.setOrder(60)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_TIPO_VEHICULO(ft):
  attr = ft.add("TIPO_VEHICULO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TIPO_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Tipo_vehiculo')
  attr.setOrder(70)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_TIPO_VEHICULO')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'dynform.dropdown', u'label')

def add_attribute_MMA(ft):
  attr = ft.add("MMA",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MMA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_MMA')
  attr.setOrder(80)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_MMA')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_MARCA_NOMBRE(ft):
  attr = ft.add("MARCA_NOMBRE",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MARCA_NOMBRE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Marca')
  attr.setOrder(90)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_MODELO(ft):
  attr = ft.add("MODELO",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MODELO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Modelo')
  attr.setOrder(100)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ITV(ft):
  attr = ft.add("ITV",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ITV')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_ITV')
  attr.setOrder(110)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_ITV')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_SEGURO(ft):
  attr = ft.add("SEGURO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SEGURO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Seguro')
  attr.setOrder(120)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_GENERICO2')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_NUM_OCUPANTES(ft):
  attr = ft.add("NUM_OCUPANTES",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'NUM_OCUPANTES')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Numero_de_ocupantes')
  attr.setOrder(130)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_VEHICULO_ADAPTADO(ft):
  attr = ft.add("VEHICULO_ADAPTADO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'VEHICULO_ADAPTADO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Vehiculo_adaptado')
  attr.setOrder(140)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_TRANSPORTE_ESPECIAL(ft):
  attr = ft.add("TRANSPORTE_ESPECIAL",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TRANSPORTE_ESPECIAL')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Transporte_especial')
  attr.setOrder(150)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_FUGADO(ft):
  attr = ft.add("FUGADO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FUGADO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Fugado')
  attr.setOrder(160)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_INCENDIADO(ft):
  attr = ft.add("INCENDIADO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INCENDIADO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Incendiado')
  attr.setOrder(170)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_MP(ft):
  attr = ft.add("MP",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MP')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Mercancias_peligrosas')
  attr.setOrder(180)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_MP_NUMERO_ONU(ft):
  attr = ft.add("MP_NUMERO_ONU",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MP_NUMERO_ONU')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_MP_Numero_ONU')
  attr.setOrder(190)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',CODIGO,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_ONU')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'report.attr.label', u'DESCRIPCION')

def add_attribute_DANYOS(ft):
  attr = ft.add("DANYOS",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'DANYOS')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Danyos')
  attr.setOrder(200)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_DANYOS')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'report.attr.label', u'DESCRIPCION')

def add_attribute_REMOLQUE(ft):
  attr = ft.add("REMOLQUE",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'REMOLQUE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Remolque')
  attr.setOrder(210)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'dynform.separator', u'_Remolque')

def add_attribute_SEMIREMOLQUE(ft):
  attr = ft.add("SEMIREMOLQUE",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SEMIREMOLQUE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Semiremolque')
  attr.setOrder(220)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_CARAVANA(ft):
  attr = ft.add("CARAVANA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CARAVANA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Carabana')
  attr.setOrder(230)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_REMOLQUE_OTROS(ft):
  attr = ft.add("REMOLQUE_OTROS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'REMOLQUE_OTROS')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Otros_remolques')
  attr.setOrder(240)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_POS_VIA(ft):
  attr = ft.add("POS_VIA",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'POS_VIA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Posicion_en_la_via')
  attr.setOrder(250)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_POSICION_VIA')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'report.attr.label', u'DESCRIPCION')
  tags.set(u'dynform.separator', u'_Posicion_en_la_via')

def add_attribute_APROXIMACION_NUDO(ft):
  attr = ft.add("APROXIMACION_NUDO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'APROXIMACION_NUDO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Aproximacion_a_nudo')
  attr.setOrder(260)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_NUDO_APROX')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'report.attr.label', u'DESCRIPCION')

def add_attribute_SENTIDO_CIRCULACION(ft):
  attr = ft.add("SENTIDO_CIRCULACION",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SENTIDO_CIRCULACION')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Sentido_de_la_circulacion')
  attr.setOrder(270)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_SENTIDO_CIRCULA')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'report.attr.label', u'DESCRIPCION')

def add_attribute_LUGAR_CIRCULABA(ft):
  attr = ft.add("LUGAR_CIRCULABA",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LUGAR_CIRCULABA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(True)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Lugar_por_el_que_circulaba')
  attr.setOrder(280)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_LUGAR_CIRCULA')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'report.attr.label', u'DESCRIPCION')
  tags.set(u'dynform.dropdown', u'label')

def add_attribute_FACT_LUGAR_CIRCULA(ft):
  attr = ft.add("FACT_LUGAR_CIRCULA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FACT_LUGAR_CIRCULA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Influye_el_lugar_por_el_que_circulaba')
  attr.setOrder(290)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_TACOGRAFO_DISCO(ft):
  attr = ft.add("TACOGRAFO_DISCO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TACOGRAFO_DISCO')
  attr.setGroup(u'_Tacografo')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Disco_tacografo')
  attr.setOrder(300)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_TACOGRAFO_LECTURA(ft):
  attr = ft.add("TACOGRAFO_LECTURA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TACOGRAFO_LECTURA')
  attr.setGroup(u'_Tacografo')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Lectura_tacografo')
  attr.setOrder(310)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_DESCANSO_DIARIO(ft):
  attr = ft.add("DESCANSO_DIARIO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'DESCANSO_DIARIO')
  attr.setGroup(u'_Tacografo')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Respetado_el_descanso_diario')
  attr.setOrder(320)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_HORAS_COND_CONTINU_SUP(ft):
  attr = ft.add("HORAS_COND_CONTINU_SUP",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'HORAS_COND_CONTINU_SUP')
  attr.setGroup(u'_Tacografo')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Superadas_horas_conduccion_continuada')
  attr.setOrder(330)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_HORAS_COND_DIARIA_SUP(ft):
  attr = ft.add("HORAS_COND_DIARIA_SUP",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'HORAS_COND_DIARIA_SUP')
  attr.setGroup(u'_Tacografo')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Superadas_horas_de_conduccion_diaria')
  attr.setOrder(340)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_HORAS_COND_CONTINUADAS_H(ft):
  attr = ft.add("HORAS_COND_CONTINUADAS_H",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'HORAS_COND_CONTINUADAS_H')
  attr.setGroup(u'_Tacografo')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Conduccion_continuada_horas')
  attr.setOrder(350)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_HORAS_COND_CONTINUADAS_MIN(ft):
  attr = ft.add("HORAS_COND_CONTINUADAS_MIN",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'HORAS_COND_CONTINUADAS_MIN')
  attr.setGroup(u'_Tacografo')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Conduccion_continuada_min')
  attr.setOrder(360)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_FACT_ANOMALIAS_PREVIAS(ft):
  attr = ft.add("FACT_ANOMALIAS_PREVIAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FACT_ANOMALIAS_PREVIAS')
  attr.setGroup(u'_Anomalias_previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Influyen_las_anomalias_previas')
  attr.setOrder(370)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ANOMALIAS_NINGUNA(ft):
  attr = ft.add("ANOMALIAS_NINGUNA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_NINGUNA')
  attr.setGroup(u'_Anomalias_previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AP_Aparentemente_ninguna')
  attr.setOrder(380)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ANOMALIAS_NEUMATICOS(ft):
  attr = ft.add("ANOMALIAS_NEUMATICOS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_NEUMATICOS')
  attr.setGroup(u'_Anomalias_previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AP_Neumaticos_desgastados_o_defectuosos')
  attr.setOrder(390)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ANOMALIAS_REVENTON(ft):
  attr = ft.add("ANOMALIAS_REVENTON",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_REVENTON')
  attr.setGroup(u'_Anomalias_previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AP_Reventon')
  attr.setOrder(400)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ANOMALIAS_DIRECCION(ft):
  attr = ft.add("ANOMALIAS_DIRECCION",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_DIRECCION')
  attr.setGroup(u'_Anomalias_previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AP_Direccion')
  attr.setOrder(410)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ANOMALIAS_FRENOS(ft):
  attr = ft.add("ANOMALIAS_FRENOS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_FRENOS')
  attr.setGroup(u'_Anomalias_previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AP_Frenos')
  attr.setOrder(420)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ANOMALIAS_OTRAS(ft):
  attr = ft.add("ANOMALIAS_OTRAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_OTRAS')
  attr.setGroup(u'_Anomalias_previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AP_Otras')
  attr.setOrder(430)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ANOMALIAS_OTRA(ft):
  attr = ft.add("ANOMALIAS_OTRA",8)
  attr.setSize(50)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_OTRA')
  attr.setGroup(u'_Anomalias_previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AP_Otra')
  attr.setOrder(440)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_COND(ft):
  attr = ft.add("AIRBAG_COND",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_COND')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Frontal_del_conductor')
  attr.setOrder(450)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_PAS_DEL(ft):
  attr = ft.add("AIRBAG_PAS_DEL",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_PAS_DEL')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Frontal_pasajero_delantero')
  attr.setOrder(460)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_ROD_IZDA(ft):
  attr = ft.add("AIRBAG_ROD_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_ROD_IZDA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Frontal_Rodilla_izquierdo')
  attr.setOrder(470)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_ROD_DCHA(ft):
  attr = ft.add("AIRBAG_ROD_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_ROD_DCHA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Rodilla_derecho')
  attr.setOrder(480)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_LAT_DEL_IZDA(ft):
  attr = ft.add("AIRBAG_LAT_DEL_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_DEL_IZDA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Lateral_delantero_izquierdo')
  attr.setOrder(490)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_LAT_DEL_DCHA(ft):
  attr = ft.add("AIRBAG_LAT_DEL_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_DEL_DCHA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Lateral_delantero_derecho')
  attr.setOrder(500)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_CORT_DEL_IZDA(ft):
  attr = ft.add("AIRBAG_CORT_DEL_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_DEL_IZDA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Cortina_delantero_izquierdo')
  attr.setOrder(510)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_CORT_DEL_DCHA(ft):
  attr = ft.add("AIRBAG_CORT_DEL_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_DEL_DCHA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Cortina_delantero_derecho')
  attr.setOrder(520)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_LAT_TRAS_IZDA(ft):
  attr = ft.add("AIRBAG_LAT_TRAS_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_TRAS_IZDA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Lateral_trasero_izquierdo')
  attr.setOrder(530)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_LAT_TRAS_DCHA(ft):
  attr = ft.add("AIRBAG_LAT_TRAS_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_TRAS_DCHA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Lateral_trasero_derecho')
  attr.setOrder(540)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_CORT_TRAS_IZDA(ft):
  attr = ft.add("AIRBAG_CORT_TRAS_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_TRAS_IZDA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Cortina_trasero_izquierdo')
  attr.setOrder(550)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_CORT_TRAS_DCHA(ft):
  attr = ft.add("AIRBAG_CORT_TRAS_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_TRAS_DCHA')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Cortina_trasero_derecho')
  attr.setOrder(560)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_OTROS(ft):
  attr = ft.add("AIRBAG_OTROS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_OTROS')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Otros')
  attr.setOrder(570)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AIRBAG_DESCONOCIDO(ft):
  attr = ft.add("AIRBAG_DESCONOCIDO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_DESCONOCIDO')
  attr.setGroup(u'_Airbag_disparado')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_AB_Se_desconoce')
  attr.setOrder(580)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_PASAJEROS(ft):
  attr = ft.add("PASAJEROS",34)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PASAJEROS')
  attr.setGroup(u'_Pasajeros')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(True)
  attr.setIsTime(False)
  attr.setLabel(u'PASAJEROS')
  attr.setOrder(590)
  attr.setPrecision(-1)
  attr.setReadOnly(True)
  attr.setRelationType(0)
  attr.setFeatureAttributeEmulator(u'SELECT * FROM ARENA2_PASAJEROS WHERE ARENA2_PASAJEROS.LID_VEHICULO = ARENA2_VEHICULOS.LID_VEHICULO;')
  tags = attr.getTags()
  tags.set(u'dynform.label.empty', u'True')
  tags.set(u'dal.relatedfeatures.table', u'ARENA2_PASAJEROS')
  tags.set(u'dal.relatedfeatures.columns', u'ID_PASAJERO/FECHA_NACIMIENTO/SEXO/PAIS_RESIDENCIA/PROVINCIA_RESIDENCIA/MUNICIPIO_RESIDENCIA')
  tags.set(u'dal.relatedfeatures.unique.field.name', u'LID_PASAJERO')

def add_attributes_ARENA2_VEHICULOS(ft):
  add_attribute_LID_VEHICULO(ft)
  add_attribute_ID_ACCIDENTE(ft)
  add_attribute_ID_VEHICULO(ft)
  add_attribute_SIN_CONDUCTOR(ft)
  add_attribute_LID_CONDUCTOR(ft)
  add_attribute_FECHA_MATRICULACION(ft)
  add_attribute_NACIONALIDAD(ft)
  add_attribute_TIPO_VEHICULO(ft)
  add_attribute_MMA(ft)
  add_attribute_MARCA_NOMBRE(ft)
  add_attribute_MODELO(ft)
  add_attribute_ITV(ft)
  add_attribute_SEGURO(ft)
  add_attribute_NUM_OCUPANTES(ft)
  add_attribute_VEHICULO_ADAPTADO(ft)
  add_attribute_TRANSPORTE_ESPECIAL(ft)
  add_attribute_FUGADO(ft)
  add_attribute_INCENDIADO(ft)
  add_attribute_MP(ft)
  add_attribute_MP_NUMERO_ONU(ft)
  add_attribute_DANYOS(ft)
  add_attribute_REMOLQUE(ft)
  add_attribute_SEMIREMOLQUE(ft)
  add_attribute_CARAVANA(ft)
  add_attribute_REMOLQUE_OTROS(ft)
  add_attribute_POS_VIA(ft)
  add_attribute_APROXIMACION_NUDO(ft)
  add_attribute_SENTIDO_CIRCULACION(ft)
  add_attribute_LUGAR_CIRCULABA(ft)
  add_attribute_FACT_LUGAR_CIRCULA(ft)
  add_attribute_TACOGRAFO_DISCO(ft)
  add_attribute_TACOGRAFO_LECTURA(ft)
  add_attribute_DESCANSO_DIARIO(ft)
  add_attribute_HORAS_COND_CONTINU_SUP(ft)
  add_attribute_HORAS_COND_DIARIA_SUP(ft)
  add_attribute_HORAS_COND_CONTINUADAS_H(ft)
  add_attribute_HORAS_COND_CONTINUADAS_MIN(ft)
  add_attribute_FACT_ANOMALIAS_PREVIAS(ft)
  add_attribute_ANOMALIAS_NINGUNA(ft)
  add_attribute_ANOMALIAS_NEUMATICOS(ft)
  add_attribute_ANOMALIAS_REVENTON(ft)
  add_attribute_ANOMALIAS_DIRECCION(ft)
  add_attribute_ANOMALIAS_FRENOS(ft)
  add_attribute_ANOMALIAS_OTRAS(ft)
  add_attribute_ANOMALIAS_OTRA(ft)
  add_attribute_AIRBAG_COND(ft)
  add_attribute_AIRBAG_PAS_DEL(ft)
  add_attribute_AIRBAG_ROD_IZDA(ft)
  add_attribute_AIRBAG_ROD_DCHA(ft)
  add_attribute_AIRBAG_LAT_DEL_IZDA(ft)
  add_attribute_AIRBAG_LAT_DEL_DCHA(ft)
  add_attribute_AIRBAG_CORT_DEL_IZDA(ft)
  add_attribute_AIRBAG_CORT_DEL_DCHA(ft)
  add_attribute_AIRBAG_LAT_TRAS_IZDA(ft)
  add_attribute_AIRBAG_LAT_TRAS_DCHA(ft)
  add_attribute_AIRBAG_CORT_TRAS_IZDA(ft)
  add_attribute_AIRBAG_CORT_TRAS_DCHA(ft)
  add_attribute_AIRBAG_OTROS(ft)
  add_attribute_AIRBAG_DESCONOCIDO(ft)
  add_attribute_PASAJEROS(ft)


def configurar_featuretype_ARENA2_VEHICULOS(ft):

  add_attributes_ARENA2_VEHICULOS(ft)

def crearTabla_ARENA2_VEHICULOS(connection):
  tableName = "ARENA2_VEHICULOS"
  dataManager = DALLocator.getDataManager()
  server = dataManager.openServerExplorer(
      connection.getProviderName(),
      connection
  )
  params = server.getAddParameters(tableName)
  ft = params.getDefaultFeatureType()
  configurar_featuretype_ARENA2_VEHICULOS(ft)

  server.add(tableName, params, False)

def main(*args):
    pass
