# encoding: utf-8

import gvsig

from org.gvsig.fmap.dal import DALLocator

def add_attribute_LID_CONDUCTOR(ft):
  attr = ft.add("LID_CONDUCTOR",8)
  attr.setSize(30)
  attr.setAllowIndexDuplicateds(True)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LID_CONDUCTOR')
  attr.setGroup(None)
  attr.setHidden(True)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(True)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Id_conduct')
  attr.setOrder(0)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ID_ACCIDENTE(ft):
  attr = ft.add("ID_ACCIDENTE",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ID_ACCIDENTE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Accidente')
  attr.setOrder(10)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID_ACCIDENTE')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%s',ID_ACCIDENTE)")
  attr.getForeingKey().setClosedList(False)
  attr.getForeingKey().setTableName(u'ARENA2_ACCIDENTES')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_LID_VEHICULO(ft):
  attr = ft.add("LID_VEHICULO",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LID_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Vehiculo')
  attr.setOrder(20)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'LID_VEHICULO')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%s/%s %s %s %s %s',ID_ACCIDENTE,ID_VEHICULO,TIPO_VEHICULO,NACIONALIDAD,MARCA_NOMBRE,MODELO)")
  attr.getForeingKey().setClosedList(False)
  attr.getForeingKey().setTableName(u'ARENA2_VEHICULOS')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ID_VEHICULO(ft):
  attr = ft.add("ID_VEHICULO",8)
  attr.setSize(5)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ID_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(True)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Id_vehiculo')
  attr.setOrder(30)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_POSIBLE_RESPONSABLE(ft):
  attr = ft.add("POSIBLE_RESPONSABLE",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'POSIBLE_RESPONSABLE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Posible_responsable')
  attr.setOrder(40)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_FECHA_NACIMIENTO(ft):
  attr = ft.add("FECHA_NACIMIENTO",9)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FECHA_NACIMIENTO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Fecha_nacimiento')
  attr.setOrder(50)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'dynform.separator', u'_Datos_personales')

def add_attribute_SEXO(ft):
  attr = ft.add("SEXO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SEXO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Sexo')
  attr.setOrder(60)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_SEXO')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_NACIONALIDAD(ft):
  attr = ft.add("NACIONALIDAD",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'NACIONALIDAD')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Nacionalidad')
  attr.setOrder(70)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_PAIS_RESIDENCIA(ft):
  attr = ft.add("PAIS_RESIDENCIA",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PAIS_RESIDENCIA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Pais_de_residencia')
  attr.setOrder(80)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_PROVINCIA_RESIDENCIA(ft):
  attr = ft.add("PROVINCIA_RESIDENCIA",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PROVINCIA_RESIDENCIA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Provincia_de_residencia')
  attr.setOrder(90)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_MUNICIPIO_RESIDENCIA(ft):
  attr = ft.add("MUNICIPIO_RESIDENCIA",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MUNICIPIO_RESIDENCIA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Municipio_de_residencia')
  attr.setOrder(100)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ASISTENCIA_SANITARIA(ft):
  attr = ft.add("ASISTENCIA_SANITARIA",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ASISTENCIA_SANITARIA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Asistencia_sanitaria')
  attr.setOrder(110)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_ASISTENCIA_SANITARIA')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_INFLU_FACT_ATENCION(ft):
  attr = ft.add("INFLU_FACT_ATENCION",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INFLU_FACT_ATENCION')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Influyen_factores_atencion')
  attr.setOrder(120)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'dynform.separator', u'_Posibles_errores')

def add_attribute_FACTORES_ATENCION(ft):
  attr = ft.add("FACTORES_ATENCION",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FACTORES_ATENCION')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Factores_afectan_atencion')
  attr.setOrder(130)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_FACTORES_ATENCION_COND')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_INFLU_PRES_ERROR(ft):
  attr = ft.add("INFLU_PRES_ERROR",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INFLU_PRES_ERROR')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Influyen_presuntos_errores')
  attr.setOrder(140)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_PRESUNTOS_ERRORES(ft):
  attr = ft.add("PRESUNTOS_ERRORES",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PRESUNTOS_ERRORES')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Presuntos_errores')
  attr.setOrder(150)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_ERRORES_COND')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_CARACT_PERMISO(ft):
  attr = ft.add("CARACT_PERMISO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CARACT_PERMISO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Caracteristicas_del_permiso')
  attr.setOrder(160)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_CARACTERISTICAS_PERMISO')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'dynform.separator', u'_Permiso')

def add_attribute_CLASE_PERMISO(ft):
  attr = ft.add("CLASE_PERMISO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CLASE_PERMISO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Clase_del_permiso')
  attr.setOrder(170)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_CLASE_PERMISO')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_FECHA_PERMISO(ft):
  attr = ft.add("FECHA_PERMISO",9)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FECHA_PERMISO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Fecha_permiso')
  attr.setOrder(180)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_MOTIVO_DESPLAZAMIENTO(ft):
  attr = ft.add("MOTIVO_DESPLAZAMIENTO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MOTIVO_DESPLAZAMIENTO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Motivo_desplazamiento')
  attr.setOrder(190)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_MOTIVO_DESPLAZA_COND')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'dynform.separator', u'_Desplazamiento')

def add_attribute_DESPLAZAMIENTO_PREVISTO(ft):
  attr = ft.add("DESPLAZAMIENTO_PREVISTO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'DESPLAZAMIENTO_PREVISTO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Desplazamiento_previsto')
  attr.setOrder(200)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_DESPLAZAMIENTO_PREVISTO')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ACC_SEG_CINTURON(ft):
  attr = ft.add("ACC_SEG_CINTURON",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ACC_SEG_CINTURON')
  attr.setGroup(u'_Accesorios_de_seguridad')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Cinturon')
  attr.setOrder(210)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ACC_SEG_CASCO(ft):
  attr = ft.add("ACC_SEG_CASCO",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ACC_SEG_CASCO')
  attr.setGroup(u'_Accesorios_de_seguridad')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Casco')
  attr.setOrder(220)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_ACC_SEG_CASCO')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ACC_SEG_BRAZOS(ft):
  attr = ft.add("ACC_SEG_BRAZOS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ACC_SEG_BRAZOS')
  attr.setGroup(u'_Accesorios_de_seguridad')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Brazos')
  attr.setOrder(230)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'dynform.separator', u'_Accesorios_de_seguridad_opcionales')

def add_attribute_ACC_SEG_ESPALDA(ft):
  attr = ft.add("ACC_SEG_ESPALDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ACC_SEG_ESPALDA')
  attr.setGroup(u'_Accesorios_de_seguridad')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Espalda')
  attr.setOrder(240)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ACC_SEG_TORSO(ft):
  attr = ft.add("ACC_SEG_TORSO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ACC_SEG_TORSO')
  attr.setGroup(u'_Accesorios_de_seguridad')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Torso')
  attr.setOrder(250)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ACC_SEG_MANOS(ft):
  attr = ft.add("ACC_SEG_MANOS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ACC_SEG_MANOS')
  attr.setGroup(u'_Accesorios_de_seguridad')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Manos')
  attr.setOrder(260)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ACC_SEG_PIERNAS(ft):
  attr = ft.add("ACC_SEG_PIERNAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ACC_SEG_PIERNAS')
  attr.setGroup(u'_Accesorios_de_seguridad')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Piernas')
  attr.setOrder(270)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ACC_SEG_PIES(ft):
  attr = ft.add("ACC_SEG_PIES",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ACC_SEG_PIES')
  attr.setGroup(u'_Accesorios_de_seguridad')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Pies')
  attr.setOrder(280)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_ACC_SEG_PRENDA_REF(ft):
  attr = ft.add("ACC_SEG_PRENDA_REF",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ACC_SEG_PRENDA_REF')
  attr.setGroup(u'_Accesorios_de_seguridad')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Prenda_reflectante')
  attr.setOrder(290)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_INFLU_ALCOHOL(ft):
  attr = ft.add("INFLU_ALCOHOL",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INFLU_ALCOHOL')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Influye_el_alcohol')
  attr.setOrder(300)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'dynform.separator', u'_Prueba_de_alcohol')

def add_attribute_PRUEBA_ALCOHOLEMIA(ft):
  attr = ft.add("PRUEBA_ALCOHOLEMIA",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PRUEBA_ALCOHOLEMIA')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Prueba_en_aire')
  attr.setOrder(310)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_PRUEBA_ALCOHOLEMIA')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_TASA_ALCOHOLEMIA1(ft):
  attr = ft.add("TASA_ALCOHOLEMIA1",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TASA_ALCOHOLEMIA1')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Tasa_1_en_aire_mg_l')
  attr.setOrder(320)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_TASA_ALCOHOLEMIA2(ft):
  attr = ft.add("TASA_ALCOHOLEMIA2",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TASA_ALCOHOLEMIA2')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Tasa_2_en_aire_mg_l')
  attr.setOrder(330)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_PRUEBA_ALC_SANGRE(ft):
  attr = ft.add("PRUEBA_ALC_SANGRE",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PRUEBA_ALC_SANGRE')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Prueba_en_sangre')
  attr.setOrder(340)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_SIGNOS_INFLU_ALCOHOL(ft):
  attr = ft.add("SIGNOS_INFLU_ALCOHOL",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SIGNOS_INFLU_ALCOHOL')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Signos_de_influencia_del_alcohol')
  attr.setOrder(350)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_INFLU_DROGAS(ft):
  attr = ft.add("INFLU_DROGAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INFLU_DROGAS')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Influyen_las_drogas')
  attr.setOrder(360)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')
  tags.set(u'dynform.separator', u'_Prueba_de_drogas')

def add_attribute_PRUEBA_DROGAS(ft):
  attr = ft.add("PRUEBA_DROGAS",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PRUEBA_DROGAS')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Prueba_de_drogas')
  attr.setOrder(370)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_PRUEBA_DROGAS')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_AMP(ft):
  attr = ft.add("AMP",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AMP')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Positivo_anfetaminas')
  attr.setOrder(380)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_CONFIRMADO_AMP(ft):
  attr = ft.add("CONFIRMADO_AMP",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CONFIRMADO_AMP')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Confirmado_anfetaminas')
  attr.setOrder(390)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_BDZ(ft):
  attr = ft.add("BDZ",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'BDZ')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Positivo_benzodiacepinas')
  attr.setOrder(400)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_CONFIRMADO_BDZ(ft):
  attr = ft.add("CONFIRMADO_BDZ",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CONFIRMADO_BDZ')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Confirmado_benzodiacepinas')
  attr.setOrder(410)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_COC(ft):
  attr = ft.add("COC",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'COC')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Positivo_cocaina')
  attr.setOrder(420)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_CONFIRMADO_COC(ft):
  attr = ft.add("CONFIRMADO_COC",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CONFIRMADO_COC')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Confirmado_cocaina')
  attr.setOrder(430)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_THC(ft):
  attr = ft.add("THC",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'THC')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Positivo_cannabis_y_derivados')
  attr.setOrder(440)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_CONFIRMADO_THC(ft):
  attr = ft.add("CONFIRMADO_THC",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CONFIRMADO_THC')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Confirmado_cannabis_y_derivados')
  attr.setOrder(450)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_METH(ft):
  attr = ft.add("METH",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'METH')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Positivo_metanfetaminas')
  attr.setOrder(460)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_CONFIRMADO_METH(ft):
  attr = ft.add("CONFIRMADO_METH",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CONFIRMADO_METH')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Confirmado_metanfetaminas')
  attr.setOrder(470)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_OPI(ft):
  attr = ft.add("OPI",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'OPI')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Positivo_opiaceos')
  attr.setOrder(480)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_CONFIRMADO_OPI(ft):
  attr = ft.add("CONFIRMADO_OPI",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CONFIRMADO_OPI')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Confirmado_opiaceos')
  attr.setOrder(490)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_OTRAS(ft):
  attr = ft.add("OTRAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'OTRAS')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Positivo_benzodiacepinas')
  attr.setOrder(500)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_CONFIRMADO_OTRAS(ft):
  attr = ft.add("CONFIRMADO_OTRAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CONFIRMADO_OTRAS')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Confirmado_otra_sustancias')
  attr.setOrder(510)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_SIGNOS_INFLU_DROGAS(ft):
  attr = ft.add("SIGNOS_INFLU_DROGAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SIGNOS_INFLU_DROGAS')
  attr.setGroup(u'_Pruebas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Signos_de_influencia_de_drogas')
  attr.setOrder(520)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_INFLU_PRES_INFRAC_COND(ft):
  attr = ft.add("INFLU_PRES_INFRAC_COND",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INFLU_PRES_INFRAC_COND')
  attr.setGroup(u'_Presuntas_infracciones')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Influyen_las_infracciones_del_conductor')
  attr.setOrder(530)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_PRES_INFRAC_COND(ft):
  attr = ft.add("PRES_INFRAC_COND",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PRES_INFRAC_COND')
  attr.setGroup(u'_Presuntas_infracciones')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Presuntas_infracciones_del_conductor')
  attr.setOrder(540)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_INFRACCIONES_CODUCTOR')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_PRES_INFRAC_SIN_LUCES(ft):
  attr = ft.add("PRES_INFRAC_SIN_LUCES",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PRES_INFRAC_SIN_LUCES')
  attr.setGroup(u'_Presuntas_infracciones')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Sin_luces_de_emergencia')
  attr.setOrder(550)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_PRES_INFRAC_SIN_TRIANGULO(ft):
  attr = ft.add("PRES_INFRAC_SIN_TRIANGULO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PRES_INFRAC_SIN_TRIANGULO')
  attr.setGroup(u'_Presuntas_infracciones')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Sin_triangulo_de_presenalizacion')
  attr.setOrder(560)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_INFLU_PRES_INFRAC_VEL(ft):
  attr = ft.add("INFLU_PRES_INFRAC_VEL",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INFLU_PRES_INFRAC_VEL')
  attr.setGroup(u'_Presuntas_infracciones')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Influye_infraccion_velocidad')
  attr.setOrder(570)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_PRES_INFRAC_VEL_COND(ft):
  attr = ft.add("PRES_INFRAC_VEL_COND",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PRES_INFRAC_VEL_COND')
  attr.setGroup(u'_Presuntas_infracciones')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Presuntas_infracciones_de_velocidad')
  attr.setOrder(580)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_INFRACCIONES_VELOCIDAD')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_INFLU_OTRA_INFRAC(ft):
  attr = ft.add("INFLU_OTRA_INFRAC",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INFLU_OTRA_INFRAC')
  attr.setGroup(u'_Presuntas_infracciones')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Influye_otra_infraccion')
  attr.setOrder(590)
  attr.setPrecision(-1)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attribute_OTRA_INFRAC_COND(ft):
  attr = ft.add("OTRA_INFRAC_COND",4)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'OTRA_INFRAC_COND')
  attr.setGroup(u'_Presuntas_infracciones')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'_Otra_infraccion')
  attr.setOrder(600)
  attr.setPrecision(10)
  attr.setReadOnly(False)
  attr.setRelationType(1)
  attr.getForeingKey().setCodeName(u'ID')
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(u"FORMAT('%02d - %s',ID,DESCRIPCION)")
  attr.getForeingKey().setClosedList(True)
  attr.getForeingKey().setTableName(u'ARENA2_DIC_INFRACCIONES_OTRAS')
  tags = attr.getTags()
  tags.set(u'dynform.readonly', u'True')

def add_attributes_ARENA2_CONDUCTORES(ft):
  add_attribute_LID_CONDUCTOR(ft)
  add_attribute_ID_ACCIDENTE(ft)
  add_attribute_LID_VEHICULO(ft)
  add_attribute_ID_VEHICULO(ft)
  add_attribute_POSIBLE_RESPONSABLE(ft)
  add_attribute_FECHA_NACIMIENTO(ft)
  add_attribute_SEXO(ft)
  add_attribute_NACIONALIDAD(ft)
  add_attribute_PAIS_RESIDENCIA(ft)
  add_attribute_PROVINCIA_RESIDENCIA(ft)
  add_attribute_MUNICIPIO_RESIDENCIA(ft)
  add_attribute_ASISTENCIA_SANITARIA(ft)
  add_attribute_INFLU_FACT_ATENCION(ft)
  add_attribute_FACTORES_ATENCION(ft)
  add_attribute_INFLU_PRES_ERROR(ft)
  add_attribute_PRESUNTOS_ERRORES(ft)
  add_attribute_CARACT_PERMISO(ft)
  add_attribute_CLASE_PERMISO(ft)
  add_attribute_FECHA_PERMISO(ft)
  add_attribute_MOTIVO_DESPLAZAMIENTO(ft)
  add_attribute_DESPLAZAMIENTO_PREVISTO(ft)
  add_attribute_ACC_SEG_CINTURON(ft)
  add_attribute_ACC_SEG_CASCO(ft)
  add_attribute_ACC_SEG_BRAZOS(ft)
  add_attribute_ACC_SEG_ESPALDA(ft)
  add_attribute_ACC_SEG_TORSO(ft)
  add_attribute_ACC_SEG_MANOS(ft)
  add_attribute_ACC_SEG_PIERNAS(ft)
  add_attribute_ACC_SEG_PIES(ft)
  add_attribute_ACC_SEG_PRENDA_REF(ft)
  add_attribute_INFLU_ALCOHOL(ft)
  add_attribute_PRUEBA_ALCOHOLEMIA(ft)
  add_attribute_TASA_ALCOHOLEMIA1(ft)
  add_attribute_TASA_ALCOHOLEMIA2(ft)
  add_attribute_PRUEBA_ALC_SANGRE(ft)
  add_attribute_SIGNOS_INFLU_ALCOHOL(ft)
  add_attribute_INFLU_DROGAS(ft)
  add_attribute_PRUEBA_DROGAS(ft)
  add_attribute_AMP(ft)
  add_attribute_CONFIRMADO_AMP(ft)
  add_attribute_BDZ(ft)
  add_attribute_CONFIRMADO_BDZ(ft)
  add_attribute_COC(ft)
  add_attribute_CONFIRMADO_COC(ft)
  add_attribute_THC(ft)
  add_attribute_CONFIRMADO_THC(ft)
  add_attribute_METH(ft)
  add_attribute_CONFIRMADO_METH(ft)
  add_attribute_OPI(ft)
  add_attribute_CONFIRMADO_OPI(ft)
  add_attribute_OTRAS(ft)
  add_attribute_CONFIRMADO_OTRAS(ft)
  add_attribute_SIGNOS_INFLU_DROGAS(ft)
  add_attribute_INFLU_PRES_INFRAC_COND(ft)
  add_attribute_PRES_INFRAC_COND(ft)
  add_attribute_PRES_INFRAC_SIN_LUCES(ft)
  add_attribute_PRES_INFRAC_SIN_TRIANGULO(ft)
  add_attribute_INFLU_PRES_INFRAC_VEL(ft)
  add_attribute_PRES_INFRAC_VEL_COND(ft)
  add_attribute_INFLU_OTRA_INFRAC(ft)
  add_attribute_OTRA_INFRAC_COND(ft)


def configurar_featuretype_ARENA2_CONDUCTORES(ft):

  add_attributes_ARENA2_CONDUCTORES(ft)

def crearTabla_ARENA2_CONDUCTORES(connection):
  tableName = "ARENA2_CONDUCTORES"
  dataManager = DALLocator.getDataManager()
  server = dataManager.openServerExplorer(
      connection.getProviderName(),
      connection
  )
  params = server.getAddParameters(tableName)
  ft = params.getDefaultFeatureType()
  configurar_featuretype_ARENA2_CONDUCTORES(ft)

  server.add(tableName, params, False)

def main(*args):
    pass
