# encoding: utf-8

import gvsig

from org.gvsig.fmap.dal import DALLocator

def crearTablaVehiculos(connection):
  tableName = "ARENA2_VEHICULOS"
  dataManager = DALLocator.getDataManager()
  server = dataManager.openServerExplorer(
      connection.getExplorerName(),
      connection
  )
  params = server.getAddParameters(tableName)
  ft = params.getDefaultFeatureType()

  attr = ft.add("LID_VEHICULO",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LID_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(True)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'LID_VEHICULO')
  attr.setMandatory(False)
  attr.setOrder(0)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("ID_ACCIDENTE",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ID_ACCIDENTE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Accidente')
  attr.setMandatory(False)
  attr.setOrder(10)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getForeingKey().setCodeName(None)
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(None)
  attr.getForeingKey().setSelectable(False)
  attr.getForeingKey().setTableName(None)

  attr = ft.add("ID_VEHICULO",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ID_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Cod. vehiculo')
  attr.setMandatory(False)
  attr.setOrder(20)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("SIN_CONDUCTOR",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SIN_CONDUCTOR')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Sin conducor')
  attr.setMandatory(False)
  attr.setOrder(30)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("LID_CONDUCTOR",8)
  attr.setSize(20)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LID_CONDUCTOR')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Conductor')
  attr.setMandatory(False)
  attr.setOrder(40)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getForeingKey().setCodeName(None)
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(None)
  attr.getForeingKey().setSelectable(False)
  attr.getForeingKey().setTableName(None)

  attr = ft.add("FECHA_MATRICULACION",9)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FECHA_MATRICULACION')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Fecha matriculacion')
  attr.setMandatory(False)
  attr.setOrder(50)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(u'Date')

  attr = ft.add("NACIONALIDAD",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'NACIONALIDAD')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Nacionalidad')
  attr.setMandatory(False)
  attr.setOrder(60)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("TIPO_VEHICULO",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TIPO_VEHICULO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Tipo vehiculo')
  attr.setMandatory(False)
  attr.setOrder(70)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getForeingKey().setCodeName(None)
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(None)
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(None)

  attr = ft.add("MARCA_NOMBRE",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MARCA_NOMBRE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Marca')
  attr.setMandatory(False)
  attr.setOrder(80)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("MODELO",8)
  attr.setSize(100)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MODELO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Modelo')
  attr.setMandatory(False)
  attr.setOrder(90)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("ITV",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ITV')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ITV')
  attr.setMandatory(False)
  attr.setOrder(100)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getForeingKey().setCodeName(None)
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(None)
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(None)

  attr = ft.add("SEGURO",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SEGURO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Seguro')
  attr.setMandatory(False)
  attr.setOrder(110)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("REMOLQUE",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'REMOLQUE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Remolque')
  attr.setMandatory(False)
  attr.setOrder(120)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("SEMIREMOLQUE",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SEMIREMOLQUE')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Semiremolque')
  attr.setMandatory(False)
  attr.setOrder(130)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("CARAVANA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'CARAVANA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Carabana')
  attr.setMandatory(False)
  attr.setOrder(140)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("REMOLQUE_OTROS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'REMOLQUE_OTROS')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Otros remolques')
  attr.setMandatory(False)
  attr.setOrder(150)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("FACT_ANOMALIAS_PREVIAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FACT_ANOMALIAS_PREVIAS')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'FACT_ANOMALIAS_PREVIAS')
  attr.setMandatory(False)
  attr.setOrder(160)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("ANOMALIAS_NINGUNA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_NINGUNA')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_NINGUNA')
  attr.setMandatory(False)
  attr.setOrder(170)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("ANOMALIAS_NEUMATICOS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_NEUMATICOS')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_NEUMATICOS')
  attr.setMandatory(False)
  attr.setOrder(180)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("ANOMALIAS_REVENTON",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_REVENTON')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_REVENTON')
  attr.setMandatory(False)
  attr.setOrder(190)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("ANOMALIAS_DIRECCION",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_DIRECCION')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_DIRECCION')
  attr.setMandatory(False)
  attr.setOrder(200)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("ANOMALIAS_FRENOS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_FRENOS')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_FRENOS')
  attr.setMandatory(False)
  attr.setOrder(210)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("ANOMALIAS_OTRAS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'ANOMALIAS_OTRAS')
  attr.setGroup(u'Anomalias previas')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'ANOMALIAS_OTRAS')
  attr.setMandatory(False)
  attr.setOrder(220)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("MP",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'MP')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Mercancias peligrosas')
  attr.setMandatory(False)
  attr.setOrder(230)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("VEHICULO_ADAPTADO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'VEHICULO_ADAPTADO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Vehiculo adaptado')
  attr.setMandatory(False)
  attr.setOrder(240)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("NUM_OCUPANTES",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'NUM_OCUPANTES')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Numero de ocupantes')
  attr.setMandatory(False)
  attr.setOrder(250)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("FUGADO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FUGADO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Fugado')
  attr.setMandatory(False)
  attr.setOrder(260)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("INCENDIADO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'INCENDIADO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Incendiado')
  attr.setMandatory(False)
  attr.setOrder(270)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("TACOGRAFO_DISCO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TACOGRAFO_DISCO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'TACOGRAFO_DISCO')
  attr.setMandatory(False)
  attr.setOrder(280)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_COND",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_COND')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_COND')
  attr.setMandatory(False)
  attr.setOrder(290)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_PAS_DEL",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_PAS_DEL')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_PAS_DEL')
  attr.setMandatory(False)
  attr.setOrder(300)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_ROD_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_ROD_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_ROD_IZDA')
  attr.setMandatory(False)
  attr.setOrder(310)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_ROD_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_ROD_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_ROD_DCHA')
  attr.setMandatory(False)
  attr.setOrder(320)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_LAT_DEL_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_DEL_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_LAT_DEL_IZDA')
  attr.setMandatory(False)
  attr.setOrder(330)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_LAT_DEL_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_DEL_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_LAT_DEL_DCHA')
  attr.setMandatory(False)
  attr.setOrder(340)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_CORT_DEL_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_DEL_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_CORT_DEL_IZDA')
  attr.setMandatory(False)
  attr.setOrder(350)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_CORT_DEL_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_DEL_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_CORT_DEL_DCHA')
  attr.setMandatory(False)
  attr.setOrder(360)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_LAT_TRAS_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_TRAS_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_LAT_TRAS_IZDA')
  attr.setMandatory(False)
  attr.setOrder(370)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_LAT_TRAS_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_LAT_TRAS_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_LAT_TRAS_DCHA')
  attr.setMandatory(False)
  attr.setOrder(380)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_CORT_TRAS_IZDA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_TRAS_IZDA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_CORT_TRAS_IZDA')
  attr.setMandatory(False)
  attr.setOrder(390)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_CORT_TRAS_DCHA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_CORT_TRAS_DCHA')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_CORT_TRAS_DCHA')
  attr.setMandatory(False)
  attr.setOrder(400)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_OTROS",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_OTROS')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_OTROS')
  attr.setMandatory(False)
  attr.setOrder(410)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("AIRBAG_DESCONOCIDO",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'AIRBAG_DESCONOCIDO')
  attr.setGroup(u'Airbag')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'AIRBAG_DESCONOCIDO')
  attr.setMandatory(False)
  attr.setOrder(420)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("TRANSPORTE_ESPECIAL",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'TRANSPORTE_ESPECIAL')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Transporte especial')
  attr.setMandatory(False)
  attr.setOrder(430)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("DANYOS",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'DANYOS')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'Da\xf1os')
  attr.setMandatory(False)
  attr.setOrder(440)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getForeingKey().setCodeName(None)
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(None)
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(None)

  attr = ft.add("POS_VIA",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'POS_VIA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'POS_VIA')
  attr.setMandatory(False)
  attr.setOrder(450)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getForeingKey().setCodeName(None)
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(None)
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(None)

  attr = ft.add("APROXIMACION_NUDO",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'APROXIMACION_NUDO')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'APROXIMACION_NUDO')
  attr.setMandatory(False)
  attr.setOrder(460)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getForeingKey().setCodeName(None)
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(None)
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(None)

  attr = ft.add("SENTIDO_CIRCULACION",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'SENTIDO_CIRCULACION')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'SENTIDO_CIRCULACION')
  attr.setMandatory(False)
  attr.setOrder(470)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getForeingKey().setCodeName(None)
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(None)
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(None)

  attr = ft.add("LUGAR_CIRCULABA",4)
  attr.setSize(10)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'LUGAR_CIRCULABA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'LUGAR_CIRCULABA')
  attr.setMandatory(False)
  attr.setOrder(480)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getForeingKey().setCodeName(None)
  attr.getForeingKey().setForeingKey(True)
  attr.getForeingKey().setLabelFormula(None)
  attr.getForeingKey().setSelectable(True)
  attr.getForeingKey().setTableName(None)

  attr = ft.add("FACT_LUGAR_CIRCULA",1)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'FACT_LUGAR_CIRCULA')
  attr.setGroup(None)
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(False)
  attr.setIsTime(False)
  attr.setLabel(u'FACT_LUGAR_CIRCULA')
  attr.setMandatory(False)
  attr.setOrder(490)
  attr.setPrecision(0)
  attr.setReadOnly(False)
  attr.setRelationType(0)
  attr.setSubtype(None)

  attr = ft.add("PASAJEROS",34)
  attr.setSize(0)
  attr.setAllowIndexDuplicateds(False)
  attr.setAllowNull(True)
  attr.setDataProfileName(None)
  attr.setDescription(u'PASAJEROS')
  attr.setGroup(u'Pasajeros')
  attr.setHidden(False)
  attr.setIsAutomatic(False)
  attr.setIsIndexAscending(True)
  attr.setIsIndexed(False)
  attr.setIsPrimaryKey(False)
  attr.setPersistent(False)
  attr.setIsReadOnly(True)
  attr.setIsTime(False)
  attr.setLabel(u'PASAJEROS')
  attr.setMandatory(False)
  attr.setOrder(500)
  attr.setPrecision(0)
  attr.setReadOnly(True)
  attr.setRelationType(0)
  attr.setSubtype(None)
  attr.getTags().set(u'dynform.label.empty', u'true')
  attr.getTags().set(u'dal.relatedfeatures.table', u'ARENA2_PASAJEROS')
  attr.getTags().set(u'dal.relatedfeatures.columns', u'ID_PASAJERO/FECHA_NACIMIENTO/SEXO/PAIS_RESIDENCIA/PROVINCIA_RESIDENCIA/MUNICIPIO_RESIDENCIA')
  attr.getTags().set(u'dal.relatedfeatures.unique.field.name', u'LID_PASAJERO')
  attr.setFeatureAttributeEmulator(u"FEATURES('ARENA2_PASAJEROS',FORMAT('LID_VEHICULO = ''%s''',LID_VEHICULO))")

  server.add(tableName, params, False)

def main(*args):
    pass
